service: backend

provider:
  name: aws
  runtime: nodejs8.10

functions:
  append:
    handler: handler.append
    environment:
      PGHOST: ${file(~/secure/elephantsql.yml):PGHOST}
      PGUSER: ${file(~/secure/elephantsql.yml):PGUSER}
      PGDATABASE: ${file(~/secure/elephantsql.yml):PGDATABASE}
      PGPASSWORD: ${file(~/secure/elephantsql.yml):PGPASSWORD}
    events:
      - http:
          path: /append
          method: post